Post component
wwi21seb-projekt/Client_BubbleMatee pull request #14
Opened 2023-12-18 13:49 UTC by pbahde

## BubbleMatee - PR Checkliste

## Usability Checklist nach den UI-Prinzipien von Nielsen - PR Checkliste

- [ ] Der Nutzer wird über jede Zustandsänderung der Anwendung informiert (z. B. Beitrag wird gepostet, Post fehlgeschlagen).
- [ ] Die verwendete Sprache und Symbole sind einfach verständlich und entsprechen den Erwartungen der Benutzer.
- [ ] Das Design (Farben/Icons...) sind stimmen mit denen der restlichen Anwendung überein.
- [ ] Der Benutzer kann alle ausgeführten Aktionen jederzeit einfach beenden und ggf. rückgängig machen.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Klare Anweisungen und Hinweise werden bereitgestellt, um Benutzerfehler zu minimieren.
- [ ] Validierung und Feedback sind vorhanden, um Benutzer vor Fehlern zu warnen (Überprüfung der Logik von Eingaben etc.).
- [ ] Das Design ist klar, minimalistisch und lenkt nicht von den Hauptaufgaben ab - Unwichtige Informationen werden vermieden.
- [ ] Informationen und Hilfestellungen finden sich an Stellen, an denen sie eventuell benötigt werden. (Besonders bei Benutzereingaben)

## Code Checkliste - Developer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Ich habe konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Wo notwendig, habe ich spezifische Interfaces genutzt, um eine klarere Typisierung zu ermöglichen.
- [ ] Ich habe "let" anstelle von "var" für die Deklaration von lokalen Variablen verwendet.
- [ ] Ich habe die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien - PascalCase für Interfaces, Typen, Enums und Klassen)
- [ ] Ich habe aussagekräftige Bezeichner für Funktionen und Variablen verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Ich habe Files, die mehr als 200 Code Zeilen haben in wiederverwendbare Komponenten aufgeteilt
- [ ] Ich habe unnötige Code-Duplikation vermieden und Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert.
- [ ] Ich habe meinen Code angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, habe ich Async/Await statt Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu machen.

## Code Checkliste - Reviewer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Es wurden konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Es wurden Interfaces genutzt, um eine klarere Typisierung zu ermöglichen, wo dies notwendig war.
- [ ] Es wurde "let" anstelle von "var" für die Deklaration lokaler Variablen verwendet.
- [ ] Es wurden die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien; PascalCase für Interfaces, Typen, Enums und Klassen).
- [ ] Es wurden aussagekräftige Bezeichner für Funktionen, Variablen und Komponenten verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Es wurden Files, die mehr als 200 Codezeilen enthalten, in wiederverwendbare Komponenten aufgeteilt.
- [ ] Es wurde unnötige Code-Duplikation vermieden, indem Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert wurde.
- [ ] Der Code wurde angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, wurde Async/Await anstelle von Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu gestalten.

2023-12-20 13:23 UTC, johannadke requested changes
Das UI sieht schonmal sehr gut aus! 
Ich habe noch ein paar Anmerkungen im Code, vor allem wegen Typisierung. 
Ansonsten ist die Piepeline noch rot. Da sollte man auch noch einmal reinschauen.

Beim Ui ist mir noch folgendes aufgefallen. Kann man bei den Kommentaren die Breite auf die Breite des Displays beschränken?

![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/093d8bda-023a-44ca-bac2-1a26cec16be8)


Ansonsten müsste man glaub noch unterscheiden, ob ein User angemeldet ist für die Interaktionen, weil Likes und Kommentare ja sowie ich es verstanden habe nur für angemeldete Nutzende zur Verfügung stehen.

Der Mülleimer beim kommentieren sollte dann vermutlich auch nur angezeigt werden, wenn etwas im Kommentarfeld geschrieben steht. Wenn nichts drinsteht, würde ich ihn also ausblenden und dann sobald etwas drinsteht einblenden.

2023-12-20 13:23 UTC, johannadke commented on src/components/posts/comments/comments-footer.svelte
> +	let newComment = '';
bitte typisieren

2023-12-20 13:23 UTC, johannadke commented on src/components/posts/post-card-elements/post-footer.svelte
> +	let isLiked = false;
typisierung

2023-12-20 13:23 UTC, johannadke commented on src/components/posts/post-card-elements/post-footer.svelte
> +	let numberOfLikes = 42; // Beispielanzahl der Likes
typisierung

2023-12-20 13:27 UTC, johannadke commented
Wenn du schonmal vorm pushen überprüfen möchtest, ob die Pipeline geht, kannst du den command pnpm prep-pr laufen lassen. Der führt dieselben checks durch und zeigt dir auch alle Fehler an

2024-01-04 11:57 UTC, pbahde commented
Der Mülleimer beim kommentieren sollte dann vermutlich auch nur angezeigt werden, wenn etwas im Kommentarfeld geschrieben steht. Wenn nichts drinsteht, würde ich ihn also ausblenden und dann sobald etwas drinsteht einblenden.

Das hatte ich ausprobiert, ich finde es sieht so etwas besser aus, weil die Aufteilung des Kommetarbereichs dann mit dem Eingabefeld besser passt :D

2024-01-08 20:10 UTC, BraunJonas commented
Ich denke es gibt ein problem in der galaxy fold einstellung, ich glaube ein Teil der Kommentare sind abgeschnitten.  
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094614/e2e6e6ce-e6d4-458d-985f-d4dfac66e17d)

2024-01-08 20:11 UTC, BraunJonas commented
Zudem sind die Dinge im Light Mode nicht gut lesbar

2024-01-08 20:15 UTC, BraunJonas commented
es wäre denke ich auch ganz gut noch mehr Kommentare in den Code einzubauen (besonders im HTML Code)

2024-01-08 20:19 UTC, BraunJonas commented
Als Idee im Post Header die Zeitumrechnung nochmals auslagern, sodass sie in anderen Komponeneten gegebenefalls wiederverwendet werden kann

2024-01-08 20:24 UTC, BraunJonas commented
Existiert die mehr Funktion auch beim Hauptkommentar oder ist das hier nich nötig... 
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094614/acff839a-55ee-41a6-9926-47195d7ce8ad)
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094614/3057e691-f5c8-4b42-8e17-20002a7c7d8a)

2024-01-08 20:30 UTC, BraunJonas commented
existiert bei den unterkommentaren ein ebenfalls mehr laden?

2024-01-12 13:00 UTC, zimmerai requested changes
Gefällt mir insgesamt sehr gut. Habe noch ein paar Kleinigkeiten gefunden

![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786770/8dee45e7-36b7-444a-a2a5-53f898d0895f)
 
Ein paar kleine Design Anstöße. Ich bin der Meinung der "short comment" ist vielleicht sogar ein Tick zu lang auf Mobile. Vielleicht nicht 200 Zeichen sondern 128 oder so

Und wozu brauchst du diesen Mülleimer unten links? Ich verstehe die Design choice an der Stelle nicht

Johanna merged ihre branch gleich, heißt dann wolltest du ja noch den Feed im Profil einbauen. 

Und bevor wir deins mergen müssen wir uns überlegen, was wir mit den ganzen "ToDos" machen. Das ist eigentlich nichts was auf main kommen sollte finde ich.

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/comments/comment-element.svelte
> +</div>
Ich würde das hier nicht mit plain html machen, sondern mit [svelte assignments](https://learn.svelte.dev/tutorial/reactive-assignments)
Beispielsweise: 
  ``` 
let moreClicked = false 
        function changeMoreClicked() {
		moreClicked = !moreClicked ;
	} 
```

Dann kann man das in den Button hauen und mithilfe von `moreClicked ? 'Weniger' : Mehr` den Button umbenennen und du kannst dann auch die Redundanz mit den Kommentaren verringern mit `moreClicked ? 'comment' : shortComment`

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/comments/comment-element.svelte
> +</div>
Wenn comment kleiner oder gleich als shortComment ist es ja egal welchen String man einsetzt und dann muss nur mit einem svelte `{#if comment <= shortComment}` der Button aus oder eingeblendet werden

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/post-card-elements/post-footer.svelte
> +			//temporär zum testen
Es gibt ja mehrere ToDo und Test Platzhalter. Wollen wir das trotzdem mergen oder die dann ein Commit vor dem Merge raus nehmen? Weil streng genommen sind das code smells

2024-01-12 13:00 UTC, zimmerai commented on src/routes/(app)/search/+page.svelte
> +	// lastPostID -> The ID of the last Post -> is needed to load the next posts
Code Smell (braucht man später aber vielleicht wieder)

2024-01-12 13:00 UTC, zimmerai commented on src/routes/(app)/search/+page.svelte
> +		//TODO: Where can we set the limit globally?
todo

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/post-card-elements/post-main.svelte
> +	//TODO Add image
Todo

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/post-card-elements/post-main.svelte
> +	//export let imageUrl: string;
code smell (braucht man aber sicher später nochmal)

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/post-card-elements/post-footer.svelte
> +	//TODO: Datenanbindung der Komponente -> wenn der Endpunkt definiert wurde
todo

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/comments/comments.svelte
> +	//TODO: Datenanbindung wenn der Endpunkt definiert ist
todo

2024-01-12 13:00 UTC, zimmerai commented on src/components/posts/comments/comments-footer.svelte
> +		//TODO: implement
todo

2024-01-13 12:13 UTC, johannadke approved these changes

2024-01-13 12:58 UTC, zimmerai approved these changes

2024-01-13 12:58 UTC, merged

2024-06-26 14:10 UTC, pbahde commented on src/components/posts/posts.svelte
> +	export let data: [];
Bitte data durch einen aussagekräftigeren Namen ersetzen