like
wwi21seb-projekt/Client_BubbleMatee pull request #41
Opened 2024-05-09 19:08 UTC by pbahde

## BubbleMatee - PR Checkliste

## Usability Checklist nach den UI-Prinzipien von Nielsen - PR Checkliste

- [ ] Der Nutzer wird über jede Zustandsänderung der Anwendung informiert (z. B. Beitrag wird gepostet, Post fehlgeschlagen).
- [ ] Die verwendete Sprache und Symbole sind einfach verständlich und entsprechen den Erwartungen der Benutzer.
- [ ] Das Design (Farben/Icons...) sind stimmen mit denen der restlichen Anwendung überein.
- [ ] Der Benutzer kann alle ausgeführten Aktionen jederzeit einfach beenden und ggf. rückgängig machen.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Klare Anweisungen und Hinweise werden bereitgestellt, um Benutzerfehler zu minimieren.
- [ ] Validierung und Feedback sind vorhanden, um Benutzer vor Fehlern zu warnen (Überprüfung der Logik von Eingaben etc.).
- [ ] Das Design ist klar, minimalistisch und lenkt nicht von den Hauptaufgaben ab - Unwichtige Informationen werden vermieden.
- [ ] Informationen und Hilfestellungen finden sich an Stellen, an denen sie eventuell benötigt werden. (Besonders bei Benutzereingaben)

## Code Checkliste - Developer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Ich habe konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Wo notwendig, habe ich spezifische Interfaces genutzt, um eine klarere Typisierung zu ermöglichen.
- [ ] Ich habe "let" anstelle von "var" für die Deklaration von lokalen Variablen verwendet.
- [ ] Ich habe die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien - PascalCase für Interfaces, Typen, Enums und Klassen)
- [ ] Ich habe aussagekräftige Bezeichner für Funktionen und Variablen verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Ich habe Files, die mehr als 200 Code Zeilen haben in wiederverwendbare Komponenten aufgeteilt
- [ ] Ich habe unnötige Code-Duplikation vermieden und Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert.
- [ ] Ich habe meinen Code angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, habe ich Async/Await statt Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu machen.

## Code Checkliste - Reviewer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Es wurden konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Es wurden Interfaces genutzt, um eine klarere Typisierung zu ermöglichen, wo dies notwendig war.
- [ ] Es wurde "let" anstelle von "var" für die Deklaration lokaler Variablen verwendet.
- [ ] Es wurden die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien; PascalCase für Interfaces, Typen, Enums und Klassen).
- [ ] Es wurden aussagekräftige Bezeichner für Funktionen, Variablen und Komponenten verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Es wurden Files, die mehr als 200 Codezeilen enthalten, in wiederverwendbare Komponenten aufgeteilt.
- [ ] Es wurde unnötige Code-Duplikation vermieden, indem Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert wurde.
- [ ] Der Code wurde angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, wurde Async/Await anstelle von Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu gestalten.

2024-05-18 12:21 UTC, johannadke commented
<img width="364" alt="Bildschirmfoto 2024-05-18 um 14 19 26" src="https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/407c7173-c10c-48e2-83ae-76ee6a408c3b">

Kannst du die Anzahl der Kommentare noch auf das was vom backend zurückkommt anpassen?

Ansonsten kann ich gerade leider noch nicht gegens Backend testen, weil die Endpunkte noch nicht stehen. Wenn die da sind, teste ich gerne nocheinmal alles und schaue dann auch den Code an :)

2024-05-18 12:34 UTC, johannadke commented
Sind die Kommentare auch teil des PR?
Weil das Posten von Kommentaren und löschen ist noch nicht implementiert im Code wenn ich das richtig gesehen habe. 

Wenn ich etwas poste als User wäre es noch gut Feedback zu bekommen, also einen Toast, damit der User weiß, ob es erfolgreich war oder nicht. (Aktuell passiert dies nicht -> s. Video)

Beim Löschen auch gerne Feedback als Toast geben. :) Oder kann man überhaupt schon löschen in der User Story? Falls nicht vergess meine Anmerkungen diesbezüglich.

Wenn keine Kommetare da sind kein load more anzeigen (siehe Video). Stattdessen vielleicht eine Meldung, dass es bisher noch keine Kommentare gibt mit einer Aufforderung der erste zu sein, der einen Kommantar verfasst.

https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/102f9b7f-ea03-4133-85af-9f3c56cf5a56

2024-05-20 17:09 UTC, pbahde commented
> <img alt="Bildschirmfoto 2024-05-18 um 14 19 26" width="364" src="https://private-user-images.githubusercontent.com/93786659/331799251-407c7173-c10c-48e2-83ae-76ee6a408c3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjQ5MTIsIm5iZiI6MTcxNjIyNDYxMiwicGF0aCI6Ii85Mzc4NjY1OS8zMzE3OTkyNTEtNDA3YzcxNzMtYzEwYy00OGUyLTgzYWUtNzZlZTZhNDA4YzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE3MDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOGY0NWZhMjI1YjFjMDJlYmNiMWYxNjFhZTVmMDczZGJiM2EzNTgzOTc1ZjNmNjZjM2U5OWM1YjQwNWRiODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.upuvQ_TobjlvAVUUVPKO0DSxbmQQs0K8h8vDs93DCa8">
> Kannst du die Anzahl der Kommentare noch auf das was vom backend zurückkommt anpassen?
> 
> Ansonsten kann ich gerade leider noch nicht gegens Backend testen, weil die Endpunkte noch nicht stehen. Wenn die da sind, teste ich gerne nocheinmal alles und schaue dann auch den Code an :)

Also bisher kommt noch nichts von dem Backend zurück. Also eigentlich würde es ja Sinn ergeben die Anzal der Kommentare wie bei den Likes zurückzugeben und nicht erst, wenn man die Kommentare lädt. So hatten wird das eigentlich auch vereinbart. Aber auf Postman fehlt das noch...

Deswegen würde ich damit noch warten

2024-05-21 09:14 UTC, zimmerai requested changes
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786770/b5dcb7ef-6847-49f4-9442-a5ef401e4ddb)
Beim senden eines Kommentars kommt ein Error. Ist es möglich nach dem Kommentieren neu zu laden? Oder vielleicht kann man das Modal dann auch schließen, aber das ist eventuell eine blöde User Experience

2024-05-21 09:14 UTC, zimmerai commented on package-lock.json
Warum wurde da so viel verändert? Was hast du hier gemacht?

2024-05-21 09:20 UTC, zimmerai commented on package-lock.json
Müsste sich nicht die pnpm-lock.yaml verändern? Ich verstehe auch gar nicht, warum wir überhaupt ne package-lock.json haben xD

2024-05-21 13:57 UTC, pbahde commented
> ![image](https://private-user-images.githubusercontent.com/93786770/332361424-b5dcb7ef-6847-49f4-9442-a5ef401e4ddb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTg0NTEsIm5iZiI6MTcxNjI5ODE1MSwicGF0aCI6Ii85Mzc4Njc3MC8zMzIzNjE0MjQtYjVkY2I3ZWYtNjg0Ny00OWY0LTk0NDItYTVlZjQwMWU0ZGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEzMjkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNDhlNjdkMjBkNDhmOGQ0OTVjNjBlYTIwODhhZTQ5MWZjMmQ4MTQ2YjZmNTJkNmViMmIyNjE2ODEwOWI4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vgaHT62zuWZa33_xslStYYbo8C41Grl_fgDk-UiodLA) Beim senden eines Kommentars kommt ein Error. Ist es möglich nach dem Kommentieren neu zu laden? Oder vielleicht kann man das Modal dann auch schließen, aber das ist eventuell eine blöde User Experience

Das müsste der Fehler vom Backend sein.

Wenn man postet wird der eigene Kommentar angezeigt. Um völlig neue kommentare zu laden müsste man die seite neu laden...

2024-05-22 07:30 UTC, zimmerai requested changes
Mach die "10 Millionen" dann solange wie es das vom Backend nicht gibt bitte weg. Dann können wir das mergen

2024-05-22 07:34 UTC, zimmerai requested changes
Wir hätten vielleicht die merge conflicts gemeinsam fixen müssen

2024-05-22 07:34 UTC, zimmerai commented on src/components/posts/comments/comment-element.svelte
> +					const currenPath = $page.url.pathname.split('/')[1];
Du hast wohl main falsch in deine Branch gemerged... Das ist wahrscheinlich nicht der einzige Fehler :(

2024-05-22 08:04 UTC, zimmerai commented
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786770/03e7f0b3-092d-421b-aa93-5825d0c54ed1)
Könntest du das bitte trotzdem irgendwie einreihen? Vielleicht mit nem beschreibenden Text oder mit CSS hoch schieben

2024-05-23 17:04 UTC, merged