feat: implement first draft of chat feature
wwi21seb-projekt/Client_BubbleMatee pull request #46
Opened 2024-05-30 15:34 UTC by zimmerai

## BubbleMatee - PR Checkliste

## Usability Checklist nach den UI-Prinzipien von Nielsen - PR Checkliste

- [ ] Der Nutzer wird über jede Zustandsänderung der Anwendung informiert (z. B. Beitrag wird gepostet, Post fehlgeschlagen).
- [ ] Die verwendete Sprache und Symbole sind einfach verständlich und entsprechen den Erwartungen der Benutzer.
- [ ] Das Design (Farben/Icons...) sind stimmen mit denen der restlichen Anwendung überein.
- [ ] Der Benutzer kann alle ausgeführten Aktionen jederzeit einfach beenden und ggf. rückgängig machen.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Klare Anweisungen und Hinweise werden bereitgestellt, um Benutzerfehler zu minimieren.
- [ ] Validierung und Feedback sind vorhanden, um Benutzer vor Fehlern zu warnen (Überprüfung der Logik von Eingaben etc.).
- [ ] Das Design ist klar, minimalistisch und lenkt nicht von den Hauptaufgaben ab - Unwichtige Informationen werden vermieden.
- [ ] Informationen und Hilfestellungen finden sich an Stellen, an denen sie eventuell benötigt werden. (Besonders bei Benutzereingaben)

## Code Checkliste - Developer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Ich habe konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Wo notwendig, habe ich spezifische Interfaces genutzt, um eine klarere Typisierung zu ermöglichen.
- [ ] Ich habe "let" anstelle von "var" für die Deklaration von lokalen Variablen verwendet.
- [ ] Ich habe die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien - PascalCase für Interfaces, Typen, Enums und Klassen)
- [ ] Ich habe aussagekräftige Bezeichner für Funktionen und Variablen verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Ich habe Files, die mehr als 200 Code Zeilen haben in wiederverwendbare Komponenten aufgeteilt
- [ ] Ich habe unnötige Code-Duplikation vermieden und Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert.
- [ ] Ich habe meinen Code angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, habe ich Async/Await statt Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu machen.

## Code Checkliste - Reviewer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Es wurden konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Es wurden Interfaces genutzt, um eine klarere Typisierung zu ermöglichen, wo dies notwendig war.
- [ ] Es wurde "let" anstelle von "var" für die Deklaration lokaler Variablen verwendet.
- [ ] Es wurden die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien; PascalCase für Interfaces, Typen, Enums und Klassen).
- [ ] Es wurden aussagekräftige Bezeichner für Funktionen, Variablen und Komponenten verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Es wurden Files, die mehr als 200 Codezeilen enthalten, in wiederverwendbare Komponenten aufgeteilt.
- [ ] Es wurde unnötige Code-Duplikation vermieden, indem Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert wurde.
- [ ] Der Code wurde angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, wurde Async/Await anstelle von Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu gestalten.

2024-06-06 15:44 UTC, pbahde commented
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094589/e7b03b23-96d8-4b89-8887-323ae89d23f2)


finde die Dimensionen ein bisschen komisch. also rechts sehr groß... Aber muss nicht unbedingt geändert werden :D

2024-06-06 15:45 UTC, pbahde commented
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094589/805262e8-050e-421a-8aaa-ee8290e37484)
Hat dieses + irgendeine Funktion?

2024-06-06 15:52 UTC, pbahde commented
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/95094589/e2b13ae2-0062-4252-9620-fd2b8abf0357)


wieso ist der Eingabebereich soweit oben?

2024-06-06 16:01 UTC, pbahde commented on src/components/search/search-tabs.svelte
> +	export let chipString: string;
Haha :D das musste ich auch schon fixxen :DD keine Ahnung wie das auf den main gekommen ist :D

2024-06-09 12:16 UTC, zimmerai commented
> ![image](https://private-user-images.githubusercontent.com/95094589/337338404-e2b13ae2-0062-4252-9620-fd2b8abf0357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzUxNDQsIm5iZiI6MTcxNzkzNDg0NCwicGF0aCI6Ii85NTA5NDU4OS8zMzczMzg0MDQtZTJiMTNhZTItMDA2Mi00MjUyLTk2MjAtZmQyYjhhYmYwMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEyMDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDE5ODVhMzdiNGMzMzE1YjBjNDZkOTQ3YTY0OTliYzgyYTdjMTJjNTZhZWIyZmY2M2NmZTViMWIxOTc3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oo8apm7lWepjEyIOU92KjfutvCAyXMOeIuzud7VmtL0)
> 
> wieso ist der Eingabebereich soweit oben?

Das CSS ist dafür irgendwie sehr unangenehm. Ich würde das für den Branch nicht versuchen zu fixen

2024-06-09 12:49 UTC, johannadke requested changes

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/[chatId]/+server.ts
> + * Handles GET requests to retrieve posts.
to retrieve messages of a chat

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/+server.ts
> + * Handles POST requests for commenting a post.
for creating a chat

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/+server.ts
> + * @returns The response containing registration data or an error.
containing ...

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/+server.ts
> + * Handles GET requests to retrieve global or personal feed.
to retrieve all chat of a user

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/+server.ts
> + * @returns The response containing feed data or an error.
containing the data of about all chat partners

2024-06-09 12:49 UTC, johannadke commented on src/routes/api/chats/[chatId]/+server.ts
> + * @returns The response containing feed data or an error.
...

2024-06-09 12:59 UTC, johannadke approved these changes
sehr schön :)

2024-06-09 13:00 UTC, merged