Pictures and week update
wwi21seb-projekt/Client_BubbleMatee pull request #58
Opened 2024-06-17 14:34 UTC by pbahde

## BubbleMatee - PR Checkliste

## Usability Checklist nach den UI-Prinzipien von Nielsen - PR Checkliste

- [ ] Der Nutzer wird über jede Zustandsänderung der Anwendung informiert (z. B. Beitrag wird gepostet, Post fehlgeschlagen).
- [ ] Die verwendete Sprache und Symbole sind einfach verständlich und entsprechen den Erwartungen der Benutzer.
- [ ] Das Design (Farben/Icons...) sind stimmen mit denen der restlichen Anwendung überein.
- [ ] Der Benutzer kann alle ausgeführten Aktionen jederzeit einfach beenden und ggf. rückgängig machen.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Der Nutzer sieht jederzeit, in welchem Bereich der Anwendung er sich befindet und wie er auf die Hauptseiten zurückgelangt.
- [ ] Klare Anweisungen und Hinweise werden bereitgestellt, um Benutzerfehler zu minimieren.
- [ ] Validierung und Feedback sind vorhanden, um Benutzer vor Fehlern zu warnen (Überprüfung der Logik von Eingaben etc.).
- [ ] Das Design ist klar, minimalistisch und lenkt nicht von den Hauptaufgaben ab - Unwichtige Informationen werden vermieden.
- [ ] Informationen und Hilfestellungen finden sich an Stellen, an denen sie eventuell benötigt werden. (Besonders bei Benutzereingaben)

## Code Checkliste - Developer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Ich habe konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Wo notwendig, habe ich spezifische Interfaces genutzt, um eine klarere Typisierung zu ermöglichen.
- [ ] Ich habe "let" anstelle von "var" für die Deklaration von lokalen Variablen verwendet.
- [ ] Ich habe die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien - PascalCase für Interfaces, Typen, Enums und Klassen)
- [ ] Ich habe aussagekräftige Bezeichner für Funktionen und Variablen verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Ich habe Files, die mehr als 200 Code Zeilen haben in wiederverwendbare Komponenten aufgeteilt
- [ ] Ich habe unnötige Code-Duplikation vermieden und Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert.
- [ ] Ich habe meinen Code angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, habe ich Async/Await statt Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu machen.

## Code Checkliste - Reviewer

### Überprüfe alle unten stehenden Punkte gewissenhaft

- [ ] Es wurden konsequent Variablen, Rückgabewerte von Funktionen, Arrays usw. typisiert.
- [ ] Es wurden Interfaces genutzt, um eine klarere Typisierung zu ermöglichen, wo dies notwendig war.
- [ ] Es wurde "let" anstelle von "var" für die Deklaration lokaler Variablen verwendet.
- [ ] Es wurden die Standard Naming Conventions eingehalten (camelCase für Variablen, Funktionen und Dateien; PascalCase für Interfaces, Typen, Enums und Klassen).
- [ ] Es wurden aussagekräftige Bezeichner für Funktionen, Variablen und Komponenten verwendet, um die Verständlichkeit des Codes zu verbessern (z. B. `let customerId` statt `let numA`).
- [ ] Es wurden Files, die mehr als 200 Codezeilen enthalten, in wiederverwendbare Komponenten aufgeteilt.
- [ ] Es wurde unnötige Code-Duplikation vermieden, indem Code, der an verschiedenen Stellen benötigt wird, in Funktionen oder Komponenten ausgelagert wurde.
- [ ] Der Code wurde angemessen kommentiert, insbesondere bei komplexen Logiken oder unklaren Stellen.
- [ ] Wo immer möglich, wurde Async/Await anstelle von Promises mit .then() für asynchrone Operationen verwendet, um den Code lesbarer zu gestalten.

2024-06-18 19:02 UTC, zimmerai requested changes
ist nur eine Kleinigkeit, aber die UX finde ich gut

2024-06-18 19:12 UTC, pbahde commented
> ist nur eine Kleinigkeit, aber die UX finde ich gut

Hab ich geändert

2024-06-18 21:24 UTC, johannadke commented
Hab noch ne KLeinigkeit:
Die Skalierung auf dem Handy wenn man ein Bild posten möchte ist sollte noch angepasst werden falls das Bild zu breit ist.
![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/a15ab831-1082-420a-ab8b-f26853c483c8)

2024-06-18 21:28 UTC, johannadke commented
Kann das Profilbild bearbeiten das zweite von oben sein? Also zwischen Profilinformationen und Passwort ändern?

![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/f360e896-6890-4569-9cd7-61d04dd549bb)

2024-06-18 21:31 UTC, johannadke commented
Wenn ich einen Post reposte und ein Bild noch anfüge, kann ich nicht runterscrollen. ALso es passt nicht auf den Bildschirm

![image](https://github.com/wwi21seb-projekt/Client_BubbleMatee/assets/93786659/8cd34609-1da8-4a61-a839-8c1d157ce491)

2024-06-18 21:57 UTC, johannadke requested changes
Wenn ein Post auf dem Handy sowohl ein Bild, als auch einen Text enthält, finde ich es für den Nutzer nicht besonders intuitiv, dass beide in einer Scrollview nebeneinander angezeigt werden. Ich denke, es wäre gut, wenn da etwas verändert wird. Vielleicht indem der Scrollbar hervorgehoben wird oder etwas vergleichbares.

2024-06-18 21:57 UTC, johannadke commented on src/components/postComponent/components/fileInput/filedropzone.svelte
> +	import { uploadRestrictions } from '../../../../static/components/index.ts';
```suggestion
	import { uploadRestrictions } from '$components';
```

2024-06-18 21:57 UTC, johannadke commented on src/components/postComponent/post-component.svelte
> +	import FileInput from './components/file-input.svelte';
```suggestion
	import { Textarea, PostButton, FileInput  } from '$components';
```

2024-06-18 21:57 UTC, johannadke commented on src/domains/ServerDomains/notifications.ts
> +import type { Picture } from '$domains/Post';
```suggestion
import type { Picture } from '$domains';
```

2024-06-18 21:57 UTC, johannadke commented on src/domains/ServerDomains/subscription.ts
> +import type { Picture } from '$domains/Post';
```suggestion
import type { Picture } from '$domains';
```

2024-06-18 21:57 UTC, johannadke commented on src/domains/ServerDomains/user.ts
> +import type { Picture } from '$domains/Post';
```suggestion
import type { Picture } from '$domains';
```

2024-06-21 13:00 UTC, zimmerai approved these changes

2024-06-21 15:02 UTC, merged

2024-06-26 07:52 UTC, pbahde commented
> Hey könnt ihr am Code noch meine Requests anpassen und ansonsten habe ich vom UI/UX Seite her noch einige Kommentare/Kleinigkeiten :) Dazu fände ich es persönlich schön, wenn sobald Foto und Text nicht mehr nebeneinander auf den Bildschirm passen es untereinander angezeigt wird.

Test

2024-06-26 07:59 UTC, pbahde commented
Wenn ein Post auf dem Handy sowohl ein Bild, als auch einen Text enthält, finde ich es für den Nutzer nicht besonders intuitiv, dass beide in einer Scrollview nebeneinander angezeigt werden. Ich denke, es wäre gut, wenn da etwas verändert wird. Vielleicht indem der Scrollbar hervorgehoben wird oder etwas vergleichbares.